/**
 * User: guoxc
 * Date: 14-10-9
 * Time: 16:35
 */
public class Test {
    public static void main(String[] args) {
//        SingleNumber.test();
//        MaximumDepthOfBinaryTree.test();
//        SameTree.test();
//        ReverseInteger.test();
//        TwoSum.test();
//        MedianOfTwoSortedArrays.test();
//        LongestSubstringWithoutRepeatingCharacters.test();
//        LongestPalindromicSubstring.test();
//        ZigZagConversion.test();
//        PalindromeNumber.test();
//        RegularExpressionMatching.test();
//        ContainerWithMostWater.test();
//        IntegerToRoman.test();
//        RomanToInteger.test();
//        LongestCommonPrefix.test();
//        ThreeSum.test();
//        ThreeSumClosest.test();
//        LetterCominationsOfAPhoneNumber.test();
//        FourSum.test();
//        RemoveNthNodeFromEndOfList.test();
//        ValidParentheses.test();
//        MergeTwoSortedLists.test();
//        GenerateParentheses.test();
//        MergeKSortedLists.test();
//        SwapNodesInPairs.test();
//        ReverseNodesInKGroup.test();
//        RemoveDuplicatesFromSortedArray.test();
//        RemoveElement.test();
//        ImplementStrStr.test();
//        DivideTwoIntegers.test();
//        SubstringWithConcatenationOfAllWords.test();
//        NextPermutation.test();
//        LongestValidParentheses.test();
//        SearchInRotatedSortedArray.test();
//        SearchInsertPosition.test();
//        SudokuSolver.test();
//        CountAndSay.test();
//        CombinationSum.test();
//        CombinationSumII.test();
//        FirstMissingPositive.test();
//        TrappingRainWater.test();
//        MultiplyStrings.test();
//        Permutations.test();
//        WildcardMatching.test();
//        JumpGame.test();
//        JumpGameII.test();
//        PermutationsII.test();
//        RotateImage.test();
//        Anagrams.test();
//        PowXN.test();
//        SpiralMatrix.test();
//        NQueens.test();
//        NQueensII.test();
//        MergeIntervals.test();
//        InsertInterval.test();
//        LengthOfLastWord.test();
//        PermutationSequence.test();
//        RotateList.test();
//        UniquePaths.test();
//        UniquePathsII.test();
//        MinimumPathSum.test();
//        ValidNumber.test();
//        PlusOne.test();
//        AddBinary.test();
//        TextJustification.test();
//        Sqrtx.test();
//        ClimbingStairs.test();
//        SimplifyPath.test();
//        EditDistance.test();
//        SetMatrixZeroes.test();
//        SearchA2dMatrix.test();
//        SortColors.test();
//        Combinations.test();
//        Subsets.test();
//        WordSearch.test();
//        RemoveDuplicatesFromSortedArrayII.test();
//        MinimumWindowSubstring.test();
//        SearchInRotatedSortedArrayII.test();
//        RemoveDuplicatesFromSortedList.test();
//        RemoveDuplicatesFromSortedListII.test();
//        LargestRectangleInHistogram.test();
//        PartitionList.test();
//        MergeSortedArray.test();
//        GrayCode.test();
//        SubsetsII.test();
//        DecodeWays.test();
//        MaximalRectangle.test();
//        ReverseLinkedListII.test();
//        RestoreIPAddresses.test();
//        BinaryTreeInorderTraversal.test();
//        UniqueBinarySearchTrees.test();
//        UniqueBinarySearchTreesII.test();
//        BinaryTreeLevelOrderTraversal.test();
//        BinaryTreeZigzagLevelOrderTraversal.test();
//        ConvertSortedArrayToBinarySearchTree.test();
//        ConvertSortedListToBinarySearchTree.test();
//        InterleavingString.test();
//        ConstructBinaryTreeFromPreorderAndInorderTraversal.test();
//        ConstructBinaryTreeFromInorderAndPostorderTraversal.test();
//        DistinctSubsequences.test();
//        PopulatingNextRightPointersInEachNodeII.test();
//        Triangle.test();
//        BestTimeToBuyAndSellStock.test();
//        RecoverBinarySearchTree.test();
//        BestTimeToBuyAndSellStockIII.test();
//        WordLadder.test();
//        LongestConsecutiveSequence.test();
//        SumRootToLeafNumbers.test();
//        SurroundedRegions.test();
//        PalindromePartitioning.test();
//        PalindromePartitioningII.test();
//        Candy.test();
//        WordBreakII.test();
//        LinkedListCycle.test();
//        InsertionSortList.test();
//        SortList.test();
//        MaximalRectangle.test();
//        WordLadderII.test();
//        MaximumProductSubarray.test();
//        MaxPointsOnALine.test();
//        MaximumGap.test();
//        FindPeakElement.test();
//        CompareVersionNumbers.test();
//        FractionToRecurringDecimal.test();
//        ExcelSheetColumnTitle.test();
//        BinarySearchTreeIterator.test();
//        DungeonGame.test();
//        LargestNumber.test();
//        RepeatedDNASequences.test();
//        ReverseBits.test();
//        HouseRobber.test();
//        NumberOfIslands.test();
//        BitwiseAndOfNumbersRange.test();
//        HappyNumber.test();
//        CountPrimes.test();
//          IsomorphicStrings.test();
//        CourseSchedule.test();
        CourseScheduleII.test();
//        MinimumSizeSubarraySum.test();
    }
    public static void pt(boolean t){
        if(!t){
            System.out.println("fail!!!!");
        }else{
            System.out.println("pass");
        }
    }
}
